version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      # Mapeamos a pasta inteira para que a API consiga ler a pasta /files ao retreinar,
      # gravar os /logs e atualizar o mlflow.db em tempo real no seu Mac/PC
      - ./:/app
    depends_on:
      - loki
    restart: unless-stopped

  mlflow:
    build: .
    container_name: mflow
    working_dir: /app
    ports:
      - "5050:5000"
    # Caminho absoluto /app/mlflow.db evita "unable to open database file" no volume
    command: mlflow ui --backend-store-uri sqlite:////app/mlflow.db --host 0.0.0.0 --port 5000
    volumes:
      - ./:/app
    restart: unless-stopped    

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:      
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards      

  node-exporter:
      image: prom/node-exporter:latest
      container_name: node-exporter
      restart: unless-stopped
      ports:
        - "9100:9100"      

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./logs:/var/log/api                      # A pasta onde a FastAPI salva o log
      - ./promtail-config.yml:/etc/promtail/config.yml # O arquivo que vamos criar abaixo
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki        