global:
  scrape_interval: 5s # Lê a API a cada 5 segundos

scrape_configs:
  - job_name: "fastapi_modelo"
    static_configs:
      # Dentro do Docker Compose, a API está no serviço "api"
      - targets: ["api:8000"]
  - job_name: "machine_resources"
    static_configs:
      - targets: ["node-exporter:9100"]
